language: c
before_install:
  - sudo apt-get update

install:
  - sudo apt-get install libopencv-dev python-opencv cmake -y

script:
  - mkdir build 
  - cd build
  - cmake ../
  - make
#   - clang -coverage -O0 hello.c -o hello
#   - ./hello
#   - gcov hello.c

# after_success:
#   - bash <(curl -s https://codecov.io/bash)